# -*- coding: utf-8 -*-
"""Network_and_Security.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14iegTcjhbJsAiL96nrp6KMZLAUEWRoMV
"""

import hashlib
def gen_md5():
  name="Harsh"
  result = name.encode("utf-8")

  gen_hash = hashlib.md5(result)
  md5_output = gen_hash.hexdigest()

  print(md5_output)

  return

gen_md5()